Copy button functionality
bitcoinsearch/chat-btc pull request #91
Opened 2024-07-10 09:52 UTC by 0tuedon

2024-07-10 12:29 UTC, Emmanuel-Develops requested changes

2024-07-10 12:29 UTC, Emmanuel-Develops commented on src/components/message/message.tsx
> +import MarkdownWrapper, { CopyButton, CopyResponseButton } from "./markdownWrapper/markdownWrapper";
`CopyButton` is not being used here

2024-07-10 12:29 UTC, Emmanuel-Develops commented on src/components/message/message.tsx
> +  console.log(type, messageBody)
remove console

2024-07-10 12:34 UTC, Emmanuel-Develops commented
The position of the copy button seems off.
<img width="1066" alt="Screenshot 2024-07-10 at 1 29 47 PM" src="https://github.com/bitcoinsearch/chat-btc/assets/62019510/25ddffa4-f475-4549-843c-628fed17b64d">

Using other chat interfaces as guidelines, it is usually at the very bottom 

chatgpt:
<img width="937" alt="Screenshot 2024-07-10 at 1 32 19 PM" src="https://github.com/bitcoinsearch/chat-btc/assets/62019510/2e807a2b-1cc9-42c0-a30e-bd18c717c111">
claude:
<img width="806" alt="Screenshot 2024-07-10 at 1 33 20 PM" src="https://github.com/bitcoinsearch/chat-btc/assets/62019510/afb4f465-c799-4ec8-b71e-a31544d2184b">

try playing around with the placement

2024-07-11 22:04 UTC, 0tuedon commented
> try playing around with the placement

I am trying to see because both examples don't have a source or follow-up questions.

doesn't displaying the copy button below make them think it's a copy-all situation?

2024-07-15 22:02 UTC, 0tuedon commented on src/components/message/markdownWrapper/markdownWrapper.tsx
> +export const CopyButton = ({ code }: { code: string }) => {
used in the `message.tsx`

2024-07-17 20:32 UTC, 0tuedon commented
@Emmanuel-Develops 
<img width="200" alt="Screenshot 2024-07-17 at 21 26 40" src="https://github.com/user-attachments/assets/9e1f8d53-6b6a-461b-88e0-0c2c8cfa5ae1">
<img width="200" alt="Screenshot 2024-07-17 at 21 23 42" src="https://github.com/user-attachments/assets/534374dc-ee53-4808-9438-943a46ab21da">
at the very bottom

2024-07-18 06:29 UTC, Extheoisah commented
> @Emmanuel-Develops <img alt="Screenshot 2024-07-17 at 21 26 40" width="200" src="https://private-user-images.githubusercontent.com/90271995/349673113-9e1f8d53-6b6a-461b-88e0-0c2c8cfa5ae1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODQ0MjAsIm5iZiI6MTcyMTI4NDEyMCwicGF0aCI6Ii85MDI3MTk5NS8zNDk2NzMxMTMtOWUxZjhkNTMtNmI2YS00NjFiLTg4ZTAtMGMyYzhjZmE1YWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA2Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNjJjMzgzN2I2NDljYjNjNGZjMmU1NjU0NmFhN2E0ZGE0MTc3ZWNiZjVlNmNkMTU4MDA3ZGViODQ1OGNmOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UOsbYurLSw7s1fIPJEpWnk_hu4fe_l8--5XeteO9sQA"> <img alt="Screenshot 2024-07-17 at 21 23 42" width="200" src="https://private-user-images.githubusercontent.com/90271995/349673121-534374dc-ee53-4808-9438-943a46ab21da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODQ0MjAsIm5iZiI6MTcyMTI4NDEyMCwicGF0aCI6Ii85MDI3MTk5NS8zNDk2NzMxMjEtNTM0Mzc0ZGMtZWU1My00ODA4LTk0MzgtOTQzYTQ2YWIyMWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA2Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZWJmMDA1M2I2YmFiODExM2RmMGI4YmIwMDljMmNlNjFkZjQwYjU0MjMyZGU4MTEyZjg1NzUzZDA1ZjkzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XZUO5DoZnCeXpdCiWUz6RX9UkH1TU7AE1A5W5SOHepI"> at the very bottom

How about we just make the text "Copy" instead of "Copy Response"? Its shorter and it follows what others use

2024-07-29 09:27 UTC, Extheoisah commented on src/components/message/message.tsx
> +             <Text fontSize="14px"  fontWeight={500}>
can we make the text clickable too? so now when you click "copy", nothing happens. We should make the both the icon and text a clickable button

2024-08-02 12:22 UTC, Extheoisah approved these changes

2024-08-02 12:22 UTC, merged